feat(user): add opengraph image generation
statsfm/web pull request #46
Opened 2024-04-08 08:14 UTC by Noctember

2024-04-08 08:24 UTC, stijnvdkolk requested changes
Just took a quick look, will test and do a more in depth review later

2024-04-08 08:24 UTC, stijnvdkolk commented on src/components/OpenGraph/User/OpenGraphDefaultUser.tsx
> +            src={`http://localhost:3001/api/image?url=${user.image}&w=256&q=75&f=image/png`}
We should use `new URL(req.url!).origin` from the api parameters here, so it will always work

2024-04-09 09:48 UTC, Noctember commented on src/components/OpenGraph/User/OpenGraphDefaultUser.tsx
> +              </svg>
Extracted it to the already existing PlusBadge file under `PlusBadgePrefilled`

2024-04-09 10:43 UTC, stijnvdkolk approved these changes

2024-04-09 10:43 UTC, merged